language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
services: docker
fast_finish: true
before_install: pip install pip-tools
install: pip-sync requirements.txt requirements-dev.txt
script: export LC_ALL=C.UTF-8 && export LANG=C.UTF-8 && export PYTHONIOENCODING=UTF-8 && python -m unittest discover -s tests
