language: python
python:
- 3.7
- 3.8
cache: pip
services: docker
before_install:
- nvm use 11
- pip install pip-tools
install: pip-sync requirements.txt requirements-dev.txt
script:
- scripts/run-tests.sh
- make --directory docs html
- touch docs/_build/html/.nojekyll
after_success:
- coverage xml
- bash <(curl -s https://codecov.io/bash)
deploy:
- provider: pypi
  username: __token__
  password:
    secure: TywbvDQWlWZ3tESQFUOBeCkJrWwlYdfn6lPu2ClNtbJQS+AYglN+UWztA3fuzygIzB9ZKqqQrGJY1Vi2/0doQOsKYTbFYCcvIJS53ineENfJmqMDFDLyBffQ9aaCYEcxPabhQRu5XdmpNWLt6nXjiediWa/9oz/Eg+F5Q7irqWGOCM+g1G7P/l331x8RQ4mCCcpHY5p/SXRUilgViN6VpZc02Z80RKeGKAjTU7CL8i1S2+gqgHeqqIL52qudoUKALjzq8hNYbfG51ArsCmy3XTDzdZMzmPo+n25ASQ49d4r82OmLIFLdMXducUxVYFdak0XB58P/vJKOocktZ/374er1ggQtnE7mw9aLSH8U+FHfoKP5uAueTrI7N1Vd5neyteWMSxALyzFK62neCu8FPHH3a1vM5kPRKfmKSN7x5uqHnJoOaSe5nWo/xrEm0AaatjGQS0BeK60d6xHUMUlD5kSEu6hEZLcFOzBd82OWtPPqSFRhuz7MrtAGdI/jQ9m6gpQhS4q/bZoQsEx9WM4vCCcHcoZ+YPla6rUt3WGYovOkWSG2EDIR+hnjFbCj+FSjPyfesNEXGKpaJ1QnnwqvUoND2gXSF2ap6EvWBp3/FYhnBuau5zObOp+14Q8lnfrXIxMaiqMqDFGTQvxOYQepaw00HH61RYl4X5lNCXNrOj0=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
  edge: true
- provider: pages:git
  token:
    secure: RAY9Oky3+ul11SQDmxWNum6CNhDJDrhelY/jh7IlecG14eOVPqu5CH2sdQ7WqkJMQ4YhZIBo1/arm+MLvdLUxHnFzxQcp2RXSIQ66rGwdKFokBVbhUz0A8ZpajDT1YW0Bn6x91tBK6RZeZ0X1SJQAdOj1C81gZqp1aUE7y3V6tlrJgPRgNv2YsgE+2neasJGbSAqumpzsVk54ldiki6WW/BEuAyY7AW89Mxw+MsRuLAPXGa08Xavrwk6PMi4YexNh4y1DHoXc3wi9thht/g2QF1qwwv97EQOYMCFvze1FFLIiSipUjA/nV3FjSKpVlQqN6JdJdQPEpoIDxEbe1Ql2Z327cEG0gw1vNgmzgB646XVIWAhEKyTsRunH7YeEiZuuKSgSeBDOGNQBm5pjq3JfY5FhOjL/NvKVFJkdu8XAXXF22bQmkL/mljdMCt2MEsh6QBc0tR5+oHeN2JfaTgTrIBuLgo9nK6yvJ5f0uMu+2v1f7mKYeI2/FMXGJbzSUADoQrUReerlj09GN+3XIAa5DeVe0goHwhSX0ft3RCZG0Qdy+/Zm6Xd4W7WRLtn3WDZ6ZA6eynLVrVnZRoXRx2tO5SoJcu+c17TMn7oIAFpmwN6Vlp98Gv9yhqELQaoYAUopqV2sdqQLWtW29UB3OTYDg14H0L4MvSvA4IDH8PF8nk=
  local_dir: docs/_build/html
  on:
    tags: true
  edge: true
