__author__ = 'Alex Pulver'
__author_email__ = 'alex.pulver@gmail.com'
__copyright__ = '2020, Alex Pulver'
__description__ = 'AWS CDK construct for AWS Chalice'
__license__ = 'MIT License'
__title__ = 'cdk-chalice'
__url__ = 'https://github.com/alexpulver/cdk-chalice'
__version__ = '0.8.2'
